### ISSUE TITLE
how can i send a group message?

### ISSUE THREAD

**Issue by paluser** [calico-crusade/palringoapi-ts#1]
i install :
npm i palringo-ts -d
then in my js file write:

`
var pal = require('palringo-ts');
`
`
var bot = pal.PalBot();
`
`
var client = pal.Client;
`
`
bot.On.LoginSuccess = function (user) { console.log('User logged in: ', user); };
`
`
bot.On.LoginFailed = function (reason) { console.log('Login Failed: ', reason); };
`
`
bot.login('email', 'password');
`

`
bot.groupMessage(18134470,'hello world') 
`
**//this line not work**
`
client.prototype.messaging.groupMessage(18134470,'hello world') 
`
**//this line not work also**

### So how can i send a group message?

**Comment by calico-crusade** [comment]
There are examples: 
https://github.com/calico-crusade/palringoapi-ts/blob/master/example/src/Test.ts

You need to make sure your email and password are correct.

**Comment by calico-crusade** [comment]
I tested it with the latest release of the package and the following code is working as expected:
```JavaScript
var pal = require('palringo-ts');

var email = ""; //Put your bot's email address here
var password = ""; //Put your bot's password here

var bot = pal.PalBot();

bot.On.LoginSuccess = function (user) { console.log('User logged in: ', user); };
bot.On.LoginFailed = function (reason) { console.log('Login Failed: ', reason); };
bot.On.GroupMessage = function(message) {
	bot.groupMessage(message.group.id, 'hello world');
};

bot.login(email, password);
```

![image](https://user-images.githubusercontent.com/31460039/77855598-6119e280-71bf-11ea-8d94-4db278904be7.png)

**Comment by calico-crusade** [comment]
I'm closing this due to lack of a response. If it is still a problem, please let me know.
